name: Docker

on: push

jobs:
  pull:
    name: 拉取并保存镜像
    runs-on: ubuntu-latest
    steps:
      - name: 执行拉取命令
        run: docker pull dreamacro/clash
      - name: 查看镜像信息
        run: docker images
      - name: 把镜像保存为压缩包
        run: docker save dreamacro/clash > clash.tar