name: Docker

on: push

jobs:
  pull:
    name: 拉取镜像
    runs-on: ubuntu-latest
    steps:
      # - name: 执行拉取命令
      #   run: docker pull dreamacro/clash
      - name: 查看镜像信息
        run: docker images
      