name: Docker

on: push

jobs:
  build_and_upload:
    name: 构建并上传镜像
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v2
      - name: 获取当前工作目录
        id: get_workspace
        run: echo "WORKSPACE=$(pwd)" >> $GITHUB_ENV
      - name: 执行拉取命令
        run: docker pull dreamacro/clash
      - name: 把镜像保存为压缩包
        run: docker save -o ${WORKSPACE}/clash.tar dreamacro/clash
      - name: 上传clash.tar作为工件
        uses: actions/upload-artifact@v4
        with:
          name: clash-image
          path: ${{ env.WORKSPACE }}/clash.tar
  download_and_use:
    name: 下载并使用镜像
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4
      - name: 下载clash.tar工件
        uses: actions/download-artifact@v2
        with:
          name: clash-image
      - name: 显示下载的文件
        run: ls -la